export default {
  common: { cancel: "Annuler", save: "Enregistrer", delete: "Supprimer", close: "Fermer", confirm: "Confirmer", copied: "Copié !", copyData: "Copier les données", copiedClipboard: "Copié dans le presse-papiers" },
  home: { title: "xKey", totalAssets: "Actifs totaux", offlineVault: "Coffre-fort hors ligne", importCSV: "Importer CSV sécurisé", importDesc: "Vos données seront chiffrées et stockées localement hors ligne.", addWallet: "Ajouter un portefeuille", noWallets: "Aucun portefeuille trouvé.", unlocking: "Déverrouillage du coffre-fort...", importSuccess: "{count} portefeuilles importés depuis {folder}", duplicatesSkipped: " ({count} doublons ignorés)", walletDeleted: "Portefeuille supprimé", folderDeleted: "Dossier \"{name}\" supprimé", backupImported: "Sauvegarde importée : {count} portefeuilles", deleteWalletConfirm: "Supprimer le portefeuille \"{name}\" ?", deleteFolderConfirm: "Supprimer tous les portefeuilles du dossier \"{name}\" ?" },
  restore: { title: "Restaurer la sauvegarde", desc: "Entrez le mot de passe utilisé lors de la création de cette sauvegarde.", placeholder: "Mot de passe de sauvegarde", button: "Restaurer", wrongPassword: "Mot de passe incorrect ou fichier corrompu" },
  settings: { title: "Paramètres", appearance: "Apparence", darkMode: "Mode sombre", lightMode: "Mode clair", language: "Langue", languageDesc: "Sélectionnez votre langue préférée", backupTitle: "Sauvegarde du coffre-fort", backupSubtitle: "Chiffré et portable — fonctionne sur tout appareil", backupInfo: "Vos portefeuilles sont chiffrés avec un mot de passe de votre choix. Cette sauvegarde peut être restaurée sur n'importe quel appareil.", createBackup: "Créer une sauvegarde chiffrée", backupPassword: "Mot de passe", confirmPassword: "Confirmer le mot de passe", passwordMin: "Min. 6 caractères", reenterPassword: "Ressaisir le mot de passe", passwordWarning: "Si vous oubliez ce mot de passe, la sauvegarde ne pourra pas être récupérée.", exportBackup: "Exporter la sauvegarde", exporting: "Exportation...", passwordMinError: "Le mot de passe doit avoir au moins 6 caractères", passwordMismatch: "Les mots de passe ne correspondent pas", exportSuccess: "Sauvegarde exportée avec succès", exportFailed: "Échec de l'exportation.", exportError: "Erreur lors de l'exportation.", dangerZone: "Zone de danger", dangerSubtitle: "Actions destructives irréversibles", wipeAll: "Effacer toutes les données", wipeDesc: "Supprime la clé de chiffrement AES et tous les portefeuilles. Impossible de les récupérer.", wipeConfirm: "ATTENTION : Tous les portefeuilles seront supprimés. Êtes-vous sûr ?", amoledMode: "AMOLED", security: "Security", securityDesc: "Auto-lock, clipboard, master password", autoLock: "Auto-Lock", autoLockSaved: "Saved", customMinutes: "Custom (min)", clipboardClear: "Clipboard Auto-Clear", clipboardSaved: "Saved", customSeconds: "Custom (sec)", masterPassword: "Master Password", masterPasswordDesc: "Extra protection for viewing keys", setMasterPassword: "Set", removeMasterPassword: "Remove", masterPasswordSet: "Enabled", masterPasswordRemoved: "Removed", removeMPConfirm: "Remove master password?", mpEnabled: "On", mpDisabled: "Off" , confirmChange: 'Changer {setting} en {value}?' },
  createWallet: { title: "Ajouter un portefeuille", tabManual: "Saisie manuelle", tabGenerate: "Génération aléatoire", generateInfo: "Générez un nouveau portefeuille avec une clé privée aléatoire sécurisée et une phrase mnémonique.", generateExplain: "Les portefeuilles sont créés par mathématiques pures — pas besoin d'Internet. La phrase suit la norme BIP-39 et fonctionne avec tout portefeuille compatible.", walletName: "Nom du portefeuille", walletNamePlaceholder: "Ex : Mon portefeuille principal", address: "Adresse", addressRequired: "(requis)", privateKey: "Clé privée", seedPhrase: "Phrase de récupération", balance: "Solde", notes: "Notes", notesPlaceholder: "Notes sur ce portefeuille...", optional: "(optionnel)", duplicateWarning: "Cette adresse existe déjà dans votre coffre-fort", fillRequired: "Veuillez remplir au moins une adresse, clé privée ou phrase de récupération", generateButton: "Générer", generateAnother: "Générer un autre", mnemonic12: "Mnémonique (12 mots)", copyMnemonic: "Copier la mnémonique", backupWarning: "Sauvegardez votre Clé Privée et votre Mnémonique MAINTENANT.", saveToVault: "Enregistrer dans le coffre-fort", walletCreated: "Portefeuille créé et enregistré", walletAdded: "Portefeuille ajouté", walletAddedDuplicate: "Portefeuille ajouté (adresse en double)", addressExplain: "L'adresse publique du portefeuille. Sûre à partager — comme un numéro de compte bancaire.", pkExplain: "La clé secrète qui contrôle ce portefeuille. Ne la partagez JAMAIS.", seedExplain: "12 ou 24 mots pouvant régénérer la clé privée. Stockez hors ligne.", network: "Network", scanQR: "Scan QR" },
  walletCard: { unnamed: "Portefeuille sans nom", noAddress: "Pas d'adresse", balanceLabel: "Solde", rename: "Renommer", delete: "Supprimer", edit: "Modifier", editWallet: "Modifier le portefeuille", saveChanges: "Enregistrer les modifications", saved: "Modifications enregistrées", added: "Ajouté le", address: "Adresse", privateKey: "Clé privée", seedPhrase: "Phrase de récupération", notes: "Notes", notesPlaceholder: "Notes...", autoHide: "(masqué auto. dans 30s)", pkWarning: "Quiconque possède cette clé a le contrôle total du portefeuille.", pin: "Pin", unpin: "Unpin", pinned: "Pinned", network: "Network", clipboardCleared: "Clipboard cleared", masterPasswordRequired: "Enter master password", masterPasswordWrong: "Wrong password", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "Search by address, name, notes...", allWallets: "Tous les portefeuilles", hasPk: "A une clé privée", hasSeed: "A une phrase de récupération", hasBalance: "Solde > 0", empty: "Solde = 0", defaultOrder: "Ordre par défaut", nameAsc: "Nom A → Z", nameDesc: "Nom Z → A", newestFirst: "Plus récent", oldestFirst: "Plus ancien", balanceHigh: "Solde élevé → bas", balanceLow: "Solde bas → élevé", addressAsc: "Adresse A → Z", allNetworks: "All Networks", pinned: "Pinned", byChain: "By Chain" },
  duplicates: { title: "Détecteur de doublons", noDuplicates: "Aucun doublon", allUnique: "Toutes les adresses sont uniques.", foundGroups: "{count} adresse(s) avec des doublons trouvée(s).", hasPK: "A PK" },
  dashboard: { title: "Analytique", totalWallets: "Total", activeBalance: "Actifs (Solde > 0)", emptyWallets: "Portefeuilles vides", withPK: "Avec clé privée", distribution: "Distribution par dossier", folders: "dossiers", totalValue: "Valeur totale", withSeed: "With Seed", chainDistribution: "By Network", importTimeline: "Timeline", networks: "networks", walletsAdded: "added" },
  exportCSV: { title: "Exporter CSV", selectColumns: "Colonnes à inclure ({count} portefeuilles)", sensitiveWarning: "Les données sensibles seront exportées en texte clair. Manipulez avec prudence.", copy: "Copier", download: "Télécharger", copySuccess: "{count} portefeuilles copiés", exportSuccess: "CSV exporté", colName: "Nom", colAddress: "Adresse", colBalance: "Solde", colFolder: "Dossier", colPrivateKey: "Clé privée", colSeedPhrase: "Phrase de récupération", colNetwork: "Network" },
  authError: { vaultLocked: "Coffre-fort verrouillé", retry: "Réessayer", wipeReset: "Effacer et réinitialiser", wipeExplain: "Votre clé de chiffrement a été perdue. Toutes les données seront supprimées définitivement.", confirmWipe: "Confirmer", wiping: "Effacement..." },
  onboarding: { slide1Title: "100% Offline", slide1Desc: "Keys never leave your device.", slide2Title: "Military Encryption", slide2Desc: "Double AES-256 with biometrics.", slide3Title: "Portable Backups", slide3Desc: "Password-protected backup files.", next: "Next", skip: "Skip", getStarted: "Get Started" },
  qrScanner: { title: "Scan QR Code", hint: "Point camera at a QR code" },

  chainBulk: { title: 'Étiquettes de chaîne', manualMode: 'Sélection manuelle', autoMode: 'Détection auto', targetChain: 'Chaîne cible', filterBy: 'Filtrer par', allWallets: 'Tous les portefeuilles', selectAll: 'Tout sélectionner', deselectAll: 'Tout désélectionner', apply: 'Appliquer {chain} à {count} portefeuilles', updated: '{count} portefeuilles mis à jour en {chain}', autoDesc: 'Détection auto de la chaîne basée sur le format.', evmNote: 'sélection manuelle requise', runAutoDetect: 'Lancer la détection auto' },
};
