export default {
  common: { cancel: "취소", save: "저장", delete: "삭제", close: "닫기", confirm: "확인", copied: "복사됨!", copyData: "데이터 복사", copiedClipboard: "클립보드에 복사됨" },
  home: { title: "xKey", totalAssets: "총 자산", offlineVault: "오프라인 키 금고", importCSV: "보안 CSV 가져오기", importDesc: "데이터는 암호화되어 오프라인으로 저장됩니다.", addWallet: "지갑 추가", noWallets: "일치하는 지갑이 없습니다.", unlocking: "키 금고 잠금 해제 중...", importSuccess: "{folder}에서 {count}개 지갑 가져옴", duplicatesSkipped: " ({count}개 중복 건너뜀)", walletDeleted: "지갑 삭제됨", folderDeleted: '폴더 "{name}" 삭제됨', backupImported: "백업 가져옴: {count}개 지갑", deleteWalletConfirm: '지갑 "{name}"을(를) 삭제하시겠습니까?', deleteFolderConfirm: '폴더 "{name}"의 모든 지갑을 삭제하시겠습니까?' },
  restore: { title: "백업 복원", desc: "이 백업을 만들 때 사용한 비밀번호를 입력하세요.", placeholder: "백업 비밀번호", button: "복원", wrongPassword: "비밀번호가 틀렸거나 파일이 손상되었습니다" },
  settings: { title: "설정", appearance: "외관", darkMode: "다크", lightMode: "라이트", amoledMode: "AMOLED", language: "언어", languageDesc: "선호하는 언어를 선택하세요", security: "보안", securityDesc: "자동 잠금, 클립보드, 마스터 비밀번호", autoLock: "자동 잠금 시간", autoLockSaved: "자동 잠금 시간 저장됨", customMinutes: "사용자 지정 (분)", clipboardClear: "클립보드 자동 삭제", clipboardSaved: "클립보드 시간 저장됨", customSeconds: "사용자 지정 (초)", masterPassword: "마스터 비밀번호", masterPasswordDesc: "개인 키 및 시드 구문 조회 시 추가 보호 계층", setMasterPassword: "마스터 비밀번호 설정", removeMasterPassword: "마스터 비밀번호 제거", masterPasswordSet: "마스터 비밀번호 활성화됨", masterPasswordRemoved: "마스터 비밀번호 제거됨", removeMPConfirm: "마스터 비밀번호를 제거하시겠습니까?", mpEnabled: "활성화", mpDisabled: "비활성화", backupTitle: "키 금고 백업", backupSubtitle: "암호화 및 이동 가능 — 모든 장치에서 사용", backupInfo: "지갑은 선택한 비밀번호로 암호화됩니다. 이 백업은 데이터 삭제 후에도 모든 장치에서 복원할 수 있습니다.", createBackup: "암호화 백업 만들기", backupPassword: "백업 비밀번호", confirmPassword: "비밀번호 확인", passwordMin: "최소 6자", reenterPassword: "비밀번호 재입력", passwordWarning: "이 비밀번호를 잊으면 백업을 복구할 수 없습니다.", exportBackup: "백업 내보내기", exporting: "내보내는 중...", passwordMinError: "비밀번호는 최소 6자 이상이어야 합니다", passwordMismatch: "비밀번호가 일치하지 않습니다", exportSuccess: "이동식 백업 내보내기 성공", exportFailed: "내보내기 실패.", exportError: "백업 내보내기 오류.", dangerZone: "위험 구역", dangerSubtitle: "되돌릴 수 없는 파괴적 작업", wipeAll: "모든 키 금고 데이터 삭제", wipeDesc: "이 작업은 AES 암호화 키와 모든 암호화된 지갑을 삭제합니다. 복구할 수 없습니다.", wipeConfirm: "경고: 이 장치의 모든 암호화된 지갑이 삭제됩니다. 이 키 금고에 대한 접근을 잃게 됩니다. 확실합니까?" , confirmChange: '{setting}을(를) {value}(으)로 변경하시겠습니까?' },
  createWallet: { title: "지갑 추가", tabManual: "수동 입력", tabGenerate: "무작위 생성", generateInfo: "안전한 무작위 개인키와 니모닉 문구로 새 지갑을 생성합니다.", generateExplain: "지갑은 순수 수학으로 생성됩니다 — 인터넷 불필요. 256비트 난수가 개인키가 됩니다. 시드 문구는 BIP-39 표준을 따르므로 호환되는 모든 지갑에서 사용할 수 있습니다.", walletName: "지갑 이름", walletNamePlaceholder: "예: 메인 지갑", address: "주소", addressRequired: "(필수)", privateKey: "개인키", seedPhrase: "시드 문구", balance: "잔액", notes: "메모", notesPlaceholder: "이 지갑에 대한 메모...", optional: "(선택)", duplicateWarning: "이 주소는 이미 키 금고에 존재합니다", fillRequired: "주소, 개인키 또는 시드 문구 중 하나 이상을 입력하세요", generateButton: "지갑 생성", generateAnother: "다시 생성", mnemonic12: "니모닉 (12단어)", copyMnemonic: "니모닉 복사", backupWarning: "지금 바로 개인키와 니모닉을 백업하세요.", saveToVault: "키 금고에 저장", walletCreated: "지갑이 생성되어 저장됨", walletAdded: "지갑이 키 금고에 추가됨", walletAddedDuplicate: "지갑 추가됨 (중복 주소)", addressExplain: "지갑의 공개 주소 (EVM 체인의 경우 0x로 시작). 공유해도 안전합니다.", pkExplain: "이 지갑을 제어하는 비밀 키. 절대 공유하지 마세요.", seedExplain: "개인키를 재생성할 수 있는 12 또는 24단어. 오프라인으로 저장하세요.", network: "네트워크", scanQR: "QR 스캔" },
  walletCard: { unnamed: "이름 없는 지갑", noAddress: "주소 없음", balanceLabel: "잔액", rename: "이름 변경", delete: "삭제", edit: "편집", editWallet: "지갑 편집", saveChanges: "변경 저장", saved: "변경 사항 저장됨", added: "추가됨", address: "주소", privateKey: "개인키", seedPhrase: "시드 문구", notes: "메모", notesPlaceholder: "메모...", autoHide: "(30초 후 자동 숨김)", pkWarning: "이 키를 가진 사람은 지갑을 완전히 제어할 수 있습니다.", pin: "고정", unpin: "고정 해제", pinned: "고정됨", network: "네트워크", clipboardCleared: "클립보드 삭제됨", masterPasswordRequired: "마스터 비밀번호를 입력하세요", masterPasswordWrong: "잘못된 마스터 비밀번호", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "주소, 이름, 메모로 검색...", allWallets: "모든 지갑", hasPk: "개인키 있음", hasSeed: "시드 문구 있음", hasBalance: "잔액 > 0", empty: "잔액 = 0", defaultOrder: "기본 순서", nameAsc: "이름 A → Z", nameDesc: "이름 Z → A", newestFirst: "최신순", oldestFirst: "오래된순", balanceHigh: "잔액 높은순", balanceLow: "잔액 낮은순", addressAsc: "주소 A → Z", allNetworks: "모든 네트워크", pinned: "고정됨", byChain: "By Chain" },
  duplicates: { title: "중복 감지기", noDuplicates: "중복 없음", allUnique: "모든 지갑 주소가 고유합니다.", foundGroups: "중복 항목이 있는 {count}개 주소를 찾았습니다. 검토하고 불필요한 항목을 삭제하세요.", hasPK: "PK 있음" },
  dashboard: { title: "분석", totalWallets: "전체 지갑", activeBalance: "활성 (잔액 > 0)", emptyWallets: "빈 지갑", withPK: "개인키 있음", withSeed: "시드 구문 있음", distribution: "폴더별 자산 분포", chainDistribution: "체인별 분포", importTimeline: "가져오기 타임라인", folders: "폴더", networks: "네트워크", totalValue: "키 금고 총 가치", walletsAdded: "지갑 추가됨" },
  exportCSV: { title: "CSV 내보내기", selectColumns: "포함할 열 선택 ({count}개 지갑)", sensitiveWarning: "민감한 데이터(개인키/시드)가 평문으로 내보내집니다. 극도로 주의하세요.", copy: "복사", download: "다운로드", copySuccess: "{count}개 지갑을 클립보드에 복사함", exportSuccess: "CSV 내보내기 성공", colName: "이름", colAddress: "주소", colBalance: "잔액", colFolder: "폴더", colPrivateKey: "개인키", colSeedPhrase: "시드 문구", colNetwork: "네트워크" },
  authError: { vaultLocked: "키 금고 잠김", retry: "인증 재시도", wipeReset: "키 금고 삭제 및 초기화", wipeExplain: "암호화 키가 손실되었거나 손상되었습니다. 모든 키 금고 데이터가 영구 삭제됩니다.", confirmWipe: "삭제 확인", wiping: "삭제 중..." },
  onboarding: { slide1Title: "100% 오프라인 보안", slide1Desc: "개인 키와 시드 구문은 기기를 떠나지 않습니다.", slide2Title: "군사급 암호화", slide2Desc: "이중 AES-256 암호화와 생체 인증.", slide3Title: "이동식 백업", slide3Desc: "암호로 보호된 백업 파일을 모든 기기에서 사용.", next: "다음", skip: "건너뛰기", getStarted: "시작하기" },
  qrScanner: { title: "QR 코드 스캔", hint: "주소, 개인 키 또는 시드 구문이 포함된 QR 코드에 카메라를 향하세요" },

  chainBulk: { title: '체인 라벨', manualMode: '수동 선택', autoMode: '자동 감지', targetChain: '대상 체인', filterBy: '필터', allWallets: '모든 지갑', selectAll: '모두 선택', deselectAll: '모두 해제', apply: '{count}개 지갑에 {chain} 적용', updated: '{count}개 지갑이 {chain}으로 업데이트됨', autoDesc: '주소 형식을 기반으로 체인을 자동 감지합니다.', evmNote: '수동 선택 필요', runAutoDetect: '자동 감지 실행' },
};
