export default {
  common: { cancel: "Cancelar", save: "Salvar", delete: "Excluir", close: "Fechar", confirm: "Confirmar", copied: "Copiado!", copyData: "Copiar dados", copiedClipboard: "Copiado para a área de transferência" },
  home: { title: "xKey", totalAssets: "Ativos totais", offlineVault: "Cofre offline", importCSV: "Importar CSV seguro", importDesc: "Seus dados serão criptografados e armazenados localmente offline.", addWallet: "Adicionar carteira", noWallets: "Nenhuma carteira encontrada.", unlocking: "Desbloqueando cofre...", importSuccess: "Importadas {count} carteiras de {folder}", duplicatesSkipped: " ({count} duplicatas ignoradas)", walletDeleted: "Carteira excluída", folderDeleted: "Pasta \"{name}\" excluída", backupImported: "Backup importado: {count} carteiras", deleteWalletConfirm: "Excluir carteira \"{name}\"?", deleteFolderConfirm: "Excluir todas as carteiras na pasta \"{name}\"?" },
  restore: { title: "Restaurar backup", desc: "Digite a senha usada ao criar este backup.", placeholder: "Senha do backup", button: "Restaurar", wrongPassword: "Senha incorreta ou arquivo corrompido" },
  settings: { title: "Configurações", appearance: "Aparência", darkMode: "Modo escuro", lightMode: "Modo claro", language: "Idioma", languageDesc: "Selecione seu idioma preferido", backupTitle: "Backup do cofre", backupSubtitle: "Criptografado e portátil — funciona em qualquer dispositivo", backupInfo: "Suas carteiras são criptografadas com uma senha escolhida por você. Este backup pode ser restaurado em qualquer dispositivo.", createBackup: "Criar backup criptografado", backupPassword: "Senha do backup", confirmPassword: "Confirmar senha", passwordMin: "Mín. 6 caracteres", reenterPassword: "Redigite a senha", passwordWarning: "Se você esquecer esta senha, o backup não poderá ser recuperado.", exportBackup: "Exportar backup", exporting: "Exportando...", passwordMinError: "A senha deve ter pelo menos 6 caracteres", passwordMismatch: "As senhas não coincidem", exportSuccess: "Backup exportado com sucesso", exportFailed: "Falha na exportação.", exportError: "Erro ao exportar backup.", dangerZone: "Zona de perigo", dangerSubtitle: "Ações destrutivas irreversíveis", wipeAll: "Apagar todos os dados do cofre", wipeDesc: "Remove a Chave AES e todas as carteiras criptografadas. Não é possível recuperar.", wipeConfirm: "AVISO: Todas as carteiras serão excluídas. Tem certeza?", amoledMode: "AMOLED", security: "Security", securityDesc: "Auto-lock, clipboard, master password", autoLock: "Auto-Lock", autoLockSaved: "Saved", customMinutes: "Custom (min)", clipboardClear: "Clipboard Auto-Clear", clipboardSaved: "Saved", customSeconds: "Custom (sec)", masterPassword: "Master Password", masterPasswordDesc: "Extra protection for viewing keys", setMasterPassword: "Set", removeMasterPassword: "Remove", masterPasswordSet: "Enabled", masterPasswordRemoved: "Removed", removeMPConfirm: "Remove master password?", mpEnabled: "On", mpDisabled: "Off" , confirmChange: 'Alterar {setting} para {value}?' },
  createWallet: { title: "Adicionar carteira", tabManual: "Entrada manual", tabGenerate: "Gerar aleatória", generateInfo: "Gere uma nova carteira com chave privada aleatória segura e frase mnemônica.", generateExplain: "Carteiras são criadas usando matemática pura — sem internet. A frase segue o padrão BIP-39 e funciona em qualquer carteira compatível.", walletName: "Nome da carteira", walletNamePlaceholder: "Ex: Minha carteira principal", address: "Endereço", addressRequired: "(obrigatório)", privateKey: "Chave privada", seedPhrase: "Frase semente", balance: "Saldo", notes: "Notas", notesPlaceholder: "Notas sobre esta carteira...", optional: "(opcional)", duplicateWarning: "Este endereço já existe no seu cofre", fillRequired: "Preencha pelo menos um endereço, chave privada ou frase semente", generateButton: "Gerar carteira", generateAnother: "Gerar outra", mnemonic12: "Mnemônica (12 palavras)", copyMnemonic: "Copiar mnemônica", backupWarning: "Faça backup da Chave Privada e Mnemônica AGORA.", saveToVault: "Salvar no cofre", walletCreated: "Carteira criada e salva", walletAdded: "Carteira adicionada ao cofre", walletAddedDuplicate: "Carteira adicionada (endereço duplicado)", addressExplain: "O endereço público da carteira. Seguro para compartilhar.", pkExplain: "A chave secreta que controla esta carteira. NUNCA compartilhe.", seedExplain: "12 ou 24 palavras que podem regenerar a chave privada. Armazene offline.", network: "Network", scanQR: "Scan QR" },
  walletCard: { unnamed: "Carteira sem nome", noAddress: "Sem endereço", balanceLabel: "Saldo", rename: "Renomear", delete: "Excluir", edit: "Editar", editWallet: "Editar carteira", saveChanges: "Salvar alterações", saved: "Alterações salvas", added: "Adicionada em", address: "Endereço", privateKey: "Chave privada", seedPhrase: "Frase semente", notes: "Notas", notesPlaceholder: "Notas...", autoHide: "(oculta em 30s)", pkWarning: "Qualquer pessoa com esta chave tem controle total.", pin: "Pin", unpin: "Unpin", pinned: "Pinned", network: "Network", clipboardCleared: "Clipboard cleared", masterPasswordRequired: "Enter master password", masterPasswordWrong: "Wrong password", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "Search by address, name, notes...", allWallets: "Todas as carteiras", hasPk: "Tem chave privada", hasSeed: "Tem frase semente", hasBalance: "Saldo > 0", empty: "Saldo = 0", defaultOrder: "Ordem padrão", nameAsc: "Nome A → Z", nameDesc: "Nome Z → A", newestFirst: "Mais recente", oldestFirst: "Mais antigo", balanceHigh: "Saldo alto → baixo", balanceLow: "Saldo baixo → alto", addressAsc: "Endereço A → Z", allNetworks: "All Networks", pinned: "Pinned", byChain: "By Chain" },
  duplicates: { title: "Detector de duplicatas", noDuplicates: "Sem duplicatas", allUnique: "Todos os endereços são únicos.", foundGroups: "{count} endereço(s) com duplicatas.", hasPK: "Tem PK" },
  dashboard: { title: "Análise", totalWallets: "Total de carteiras", activeBalance: "Ativas (Saldo > 0)", emptyWallets: "Carteiras vazias", withPK: "Com chave privada", distribution: "Distribuição por pasta", folders: "pastas", totalValue: "Valor total do cofre", withSeed: "With Seed", chainDistribution: "By Network", importTimeline: "Timeline", networks: "networks", walletsAdded: "added" },
  exportCSV: { title: "Exportar CSV", selectColumns: "Colunas ({count} carteiras)", sensitiveWarning: "Dados sensíveis serão exportados em texto simples. Manuseie com cuidado.", copy: "Copiar", download: "Baixar", copySuccess: "{count} carteiras copiadas", exportSuccess: "CSV exportado", colName: "Nome", colAddress: "Endereço", colBalance: "Saldo", colFolder: "Pasta", colPrivateKey: "Chave privada", colSeedPhrase: "Frase semente", colNetwork: "Network" },
  authError: { vaultLocked: "Cofre bloqueado", retry: "Tentar novamente", wipeReset: "Apagar e reiniciar", wipeExplain: "Chave de criptografia perdida ou corrompida. Todos os dados serão excluídos permanentemente.", confirmWipe: "Confirmar", wiping: "Apagando..." },
  onboarding: { slide1Title: "100% Offline", slide1Desc: "Keys never leave your device.", slide2Title: "Military Encryption", slide2Desc: "Double AES-256 with biometrics.", slide3Title: "Portable Backups", slide3Desc: "Password-protected backup files.", next: "Next", skip: "Skip", getStarted: "Get Started" },
  qrScanner: { title: "Scan QR Code", hint: "Point camera at a QR code" },

  chainBulk: { title: 'Rótulos de Chain', manualMode: 'Seleção manual', autoMode: 'Detecção automática', targetChain: 'Chain alvo', filterBy: 'Filtrar por', allWallets: 'Todas as carteiras', selectAll: 'Selecionar tudo', deselectAll: 'Desselecionar tudo', apply: 'Aplicar {chain} a {count} carteiras', updated: '{count} carteiras atualizadas para {chain}', autoDesc: 'Detecção automática baseada no formato do endereço.', evmNote: 'seleção manual necessária', runAutoDetect: 'Executar detecção automática' },
};
