export default {
  common: { cancel: "Отмена", save: "Сохранить", delete: "Удалить", close: "Закрыть", confirm: "Подтвердить", copied: "Скопировано!", copyData: "Копировать данные", copiedClipboard: "Скопировано в буфер обмена" },
  home: { title: "xKey", totalAssets: "Общие активы", offlineVault: "Офлайн-хранилище", importCSV: "Импорт безопасного CSV", importDesc: "Ваши данные будут зашифрованы и сохранены локально офлайн.", addWallet: "Добавить кошелёк", noWallets: "Подходящих кошельков не найдено.", unlocking: "Разблокировка хранилища...", importSuccess: "Импортировано {count} кошельков из {folder}", duplicatesSkipped: " (пропущено {count} дубликатов)", walletDeleted: "Кошелёк удалён", folderDeleted: "Папка \"{name}\" удалена", backupImported: "Резервная копия импортирована: {count} кошельков", deleteWalletConfirm: "Удалить кошелёк \"{name}\"?", deleteFolderConfirm: "Удалить все кошельки в папке \"{name}\"?" },
  restore: { title: "Восстановить резервную копию", desc: "Введите пароль, использованный при создании этой резервной копии.", placeholder: "Пароль резервной копии", button: "Восстановить", wrongPassword: "Неверный пароль или повреждённый файл" },
  settings: { title: "Настройки", appearance: "Внешний вид", darkMode: "Тёмная тема", lightMode: "Светлая тема", language: "Язык", languageDesc: "Выберите предпочитаемый язык", backupTitle: "Резервное копирование", backupSubtitle: "Зашифровано и портативно — работает на любом устройстве", backupInfo: "Ваши кошельки зашифрованы выбранным вами паролем. Эту копию можно восстановить на любом устройстве — даже после очистки данных.", createBackup: "Создать зашифрованную копию", backupPassword: "Пароль резервной копии", confirmPassword: "Подтвердить пароль", passwordMin: "Мин. 6 символов", reenterPassword: "Повторите пароль", passwordWarning: "Если вы забудете этот пароль, резервную копию невозможно будет восстановить.", exportBackup: "Экспорт копии", exporting: "Экспорт...", passwordMinError: "Пароль должен быть не менее 6 символов", passwordMismatch: "Пароли не совпадают", exportSuccess: "Портативная копия успешно экспортирована", exportFailed: "Ошибка экспорта.", exportError: "Ошибка при экспорте.", dangerZone: "Опасная зона", dangerSubtitle: "Необратимые разрушительные действия", wipeAll: "Удалить все данные хранилища", wipeDesc: "Это действие удаляет ключ шифрования AES и все зашифрованные кошельки. Восстановление невозможно.", wipeConfirm: "ВНИМАНИЕ: Все зашифрованные кошельки будут удалены с этого устройства. Вы потеряете доступ к хранилищу. Вы уверены?", amoledMode: "AMOLED", security: "Безопасность", securityDesc: "Автоблокировка, буфер, мастер-пароль", autoLock: "Автоблокировка", autoLockSaved: "Сохранено", customMinutes: "Свое (минуты)", clipboardClear: "Автоочистка буфера", clipboardSaved: "Сохранено", customSeconds: "Свое (секунды)", masterPassword: "Мастер-пароль", masterPasswordDesc: "Доп. защита для просмотра ключей", setMasterPassword: "Установить", removeMasterPassword: "Удалить", masterPasswordSet: "Включен", masterPasswordRemoved: "Удален", removeMPConfirm: "Удалить мастер-пароль?", mpEnabled: "Вкл", mpDisabled: "Выкл" , confirmChange: 'Изменить {setting} на {value}?' },
  createWallet: { title: "Добавить кошелёк", tabManual: "Ручной ввод", tabGenerate: "Случайная генерация", generateInfo: "Создайте новый кошелёк с безопасным случайным приватным ключом и мнемонической фразой.", generateExplain: "Кошельки создаются чистой математикой — интернет не нужен. 256-битное случайное число становится вашим Приватным Ключом (больше возможностей, чем атомов во вселенной). Сид-фраза следует стандарту BIP-39 и работает в любом совместимом кошельке.", walletName: "Имя кошелька", walletNamePlaceholder: "Напр.: Мой основной кошелёк", address: "Адрес", addressRequired: "(обязательно)", privateKey: "Приватный ключ", seedPhrase: "Сид-фраза", balance: "Баланс", notes: "Заметки", notesPlaceholder: "Заметки о кошельке...", optional: "(необязательно)", duplicateWarning: "Этот адрес уже есть в вашем хранилище", fillRequired: "Заполните хотя бы адрес, приватный ключ или сид-фразу", generateButton: "Создать кошелёк", generateAnother: "Создать ещё", mnemonic12: "Мнемоника (12 слов)", copyMnemonic: "Копировать мнемонику", backupWarning: "Сделайте резервную копию Приватного Ключа и Мнемоники СЕЙЧАС. После сохранения они будут зашифрованы и не могут быть восстановлены без резервной копии.", saveToVault: "Сохранить в хранилище", walletCreated: "Кошелёк создан и сохранён", walletAdded: "Кошелёк добавлен в хранилище", walletAddedDuplicate: "Кошелёк добавлен (дублирующийся адрес)", addressExplain: "Публичный адрес кошелька (начинается с 0x для EVM). Безопасно для передачи — как номер банковского счёта.", pkExplain: "Секретный ключ управления кошельком. Любой с приватным ключом может потратить все средства. НИКОГДА не делитесь.", seedExplain: "12 или 24 слова для восстановления приватного ключа. Храните офлайн, не делайте скриншоты.", network: "Сеть", scanQR: "Сканировать QR" },
  walletCard: { unnamed: "Безымянный кошелёк", noAddress: "Нет адреса", balanceLabel: "Баланс", rename: "Переименовать", delete: "Удалить", edit: "Редактировать", editWallet: "Редактировать кошелёк", saveChanges: "Сохранить изменения", saved: "Изменения сохранены", added: "Добавлен", address: "Адрес", privateKey: "Приватный ключ", seedPhrase: "Сид-фраза", notes: "Заметки", notesPlaceholder: "Заметки...", autoHide: "(скрыть через 30с)", pkWarning: "Любой с этим ключом полностью контролирует кошелёк.", pin: "Закрепить", unpin: "Открепить", pinned: "Закреплен", network: "Сеть", clipboardCleared: "Буфер очищен", masterPasswordRequired: "Введите мастер-пароль", masterPasswordWrong: "Неверный пароль", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "Поиск по адресу, имени, заметкам...", allWallets: "Все кошельки", hasPk: "Есть приватный ключ", hasSeed: "Есть сид-фраза", hasBalance: "Баланс > 0", empty: "Баланс = 0", defaultOrder: "По умолчанию", nameAsc: "Имя А → Я", nameDesc: "Имя Я → А", newestFirst: "Сначала новые", oldestFirst: "Сначала старые", balanceHigh: "Баланс выс. → низ.", balanceLow: "Баланс низ. → выс.", addressAsc: "Адрес A → Z", allNetworks: "Все сети", pinned: "Закрепленные", byChain: "By Chain" },
  duplicates: { title: "Детектор дубликатов", noDuplicates: "Дубликаты не найдены", allUnique: "Все адреса уникальны.", foundGroups: "Найдено {count} адресов с дубликатами. Проверьте и удалите ненужные.", hasPK: "Есть PK" },
  dashboard: { title: "Аналитика", totalWallets: "Всего кошельков", activeBalance: "Активные (Баланс > 0)", emptyWallets: "Пустые кошельки", withPK: "С приватным ключом", distribution: "Распределение по папкам", folders: "папки", totalValue: "Общая стоимость", withSeed: "С сид-фразой", chainDistribution: "По сетям", importTimeline: "История", networks: "сети", walletsAdded: "добавлено" },
  exportCSV: { title: "Экспорт CSV", selectColumns: "Выберите столбцы ({count} кошельков)", sensitiveWarning: "Конфиденциальные данные будут экспортированы открытым текстом. Обращайтесь крайне осторожно.", copy: "Копировать", download: "Скачать", copySuccess: "{count} кошельков скопировано", exportSuccess: "CSV экспортирован", colName: "Имя", colAddress: "Адрес", colBalance: "Баланс", colFolder: "Папка", colPrivateKey: "Приватный ключ", colSeedPhrase: "Сид-фраза", colNetwork: "Сеть" },
  authError: { vaultLocked: "Хранилище заблокировано", retry: "Повторить аутентификацию", wipeReset: "Очистить и сбросить", wipeExplain: "Ключ шифрования утерян или повреждён. Все данные хранилища будут удалены навсегда.", confirmWipe: "Подтвердить очистку", wiping: "Очистка..." },
  onboarding: { slide1Title: "100% офлайн", slide1Desc: "Ключи никогда не покидают устройство.", slide2Title: "Военное шифрование", slide2Desc: "Двойной AES-256 с биометрией.", slide3Title: "Портативные бэкапы", slide3Desc: "Защищенные паролем файлы.", next: "Далее", skip: "Пропустить", getStarted: "Начать" },
  qrScanner: { title: "Сканировать QR", hint: "Наведите камеру на QR-код" },

  chainBulk: { title: 'Метки цепочек', manualMode: 'Ручной выбор', autoMode: 'Автоопределение', targetChain: 'Целевая цепочка', filterBy: 'Фильтр', allWallets: 'Все кошельки', selectAll: 'Выбрать все', deselectAll: 'Снять все', apply: 'Применить {chain} к {count} кошелькам', updated: '{count} кошельков обновлено на {chain}', autoDesc: 'Автоматическое определение цепочки по формату адреса.', evmNote: 'требуется ручной выбор', runAutoDetect: 'Запустить автоопределение' },
};
