export default {
  common: { cancel: "ยกเลิก", save: "บันทึก", delete: "ลบ", close: "ปิด", confirm: "ยืนยัน", copied: "คัดลอกแล้ว!", copyData: "คัดลอกข้อมูล", copiedClipboard: "คัดลอกไปยังคลิปบอร์ดแล้ว" },
  home: { title: "xKey", totalAssets: "สินทรัพย์รวม", offlineVault: "ตู้เซฟออฟไลน์", importCSV: "นำเข้า CSV ที่ปลอดภัย", importDesc: "ข้อมูลจะถูกเข้ารหัสและจัดเก็บในเครื่องแบบออฟไลน์", addWallet: "เพิ่มกระเป๋าเงิน", noWallets: "ไม่พบกระเป๋าเงินที่ตรงกัน", unlocking: "กำลังปลดล็อคตู้เซฟ...", importSuccess: "นำเข้า {count} กระเป๋าเงินจาก {folder}", duplicatesSkipped: " (ข้าม {count} รายการซ้ำ)", walletDeleted: "ลบกระเป๋าเงินแล้ว", folderDeleted: "ลบโฟลเดอร์ \"{name}\" แล้ว", backupImported: "นำเข้าสำรอง: {count} กระเป๋าเงิน", deleteWalletConfirm: "ลบกระเป๋าเงิน \"{name}\"?", deleteFolderConfirm: "ลบกระเป๋าเงินทั้งหมดในโฟลเดอร์ \"{name}\"?" },
  restore: { title: "กู้คืนข้อมูลสำรอง", desc: "ป้อนรหัสผ่านที่ใช้เมื่อสร้างข้อมูลสำรองนี้", placeholder: "รหัสผ่านสำรอง", button: "กู้คืน", wrongPassword: "รหัสผ่านผิดหรือไฟล์เสียหาย" },
  settings: { title: "ตั้งค่า", appearance: "รูปลักษณ์", darkMode: "โหมดมืด", lightMode: "โหมดสว่าง", language: "ภาษา", languageDesc: "เลือกภาษาที่คุณต้องการ", backupTitle: "สำรองตู้เซฟ", backupSubtitle: "เข้ารหัสและพกพาได้ — ใช้ได้ทุกอุปกรณ์", backupInfo: "กระเป๋าเงินเข้ารหัสด้วยรหัสผ่านที่คุณเลือก สามารถกู้คืนบนอุปกรณ์ใดก็ได้", createBackup: "สร้างสำรองที่เข้ารหัส", backupPassword: "รหัสผ่านสำรอง", confirmPassword: "ยืนยันรหัสผ่าน", passwordMin: "อย่างน้อย 6 ตัวอักษร", reenterPassword: "ป้อนรหัสผ่านอีกครั้ง", passwordWarning: "หากลืมรหัสผ่านนี้ จะไม่สามารถกู้คืนข้อมูลสำรองได้", exportBackup: "ส่งออกสำรอง", exporting: "กำลังส่งออก...", passwordMinError: "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร", passwordMismatch: "รหัสผ่านไม่ตรงกัน", exportSuccess: "ส่งออกสำรองสำเร็จ", exportFailed: "ส่งออกล้มเหลว", exportError: "เกิดข้อผิดพลาดในการส่งออก", dangerZone: "โซนอันตราย", dangerSubtitle: "การกระทำที่ไม่สามารถย้อนกลับได้", wipeAll: "ลบข้อมูลตู้เซฟทั้งหมด", wipeDesc: "จะลบคีย์เข้ารหัส AES และกระเป๋าเงินทั้งหมด ไม่สามารถกู้คืนได้", wipeConfirm: "คำเตือน: กระเป๋าเงินทั้งหมดจะถูกลบ แน่ใจหรือไม่?", amoledMode: "AMOLED", security: "Security", securityDesc: "Auto-lock, clipboard, master password", autoLock: "Auto-Lock", autoLockSaved: "Saved", customMinutes: "Custom (min)", clipboardClear: "Clipboard Auto-Clear", clipboardSaved: "Saved", customSeconds: "Custom (sec)", masterPassword: "Master Password", masterPasswordDesc: "Extra protection for viewing keys", setMasterPassword: "Set", removeMasterPassword: "Remove", masterPasswordSet: "Enabled", masterPasswordRemoved: "Removed", removeMPConfirm: "Remove master password?", mpEnabled: "On", mpDisabled: "Off" , confirmChange: 'เปลี่ยน {setting} เป็น {value}?' },
  createWallet: { title: "เพิ่มกระเป๋าเงิน", tabManual: "ป้อนด้วยตนเอง", tabGenerate: "สร้างแบบสุ่ม", generateInfo: "สร้างกระเป๋าเงินใหม่ด้วยคีย์ส่วนตัวแบบสุ่มที่ปลอดภัยและวลีช่วยจำ", generateExplain: "กระเป๋าเงินสร้างขึ้นด้วยคณิตศาสตร์ล้วน — ไม่ต้องใช้อินเทอร์เน็ต วลีช่วยจำเป็นไปตามมาตรฐาน BIP-39 จึงใช้ได้กับกระเป๋าเงินที่เข้ากันได้ทุกตัว", walletName: "ชื่อกระเป๋าเงิน", walletNamePlaceholder: "เช่น: กระเป๋าเงินหลัก", address: "ที่อยู่", addressRequired: "(จำเป็น)", privateKey: "คีย์ส่วนตัว", seedPhrase: "วลีช่วยจำ", balance: "ยอดคงเหลือ", notes: "บันทึก", notesPlaceholder: "บันทึกเกี่ยวกับกระเป๋าเงินนี้...", optional: "(ไม่บังคับ)", duplicateWarning: "ที่อยู่นี้มีอยู่แล้วในตู้เซฟ", fillRequired: "กรุณากรอกที่อยู่ คีย์ส่วนตัว หรือวลีช่วยจำอย่างน้อยหนึ่งอย่าง", generateButton: "สร้างกระเป๋าเงิน", generateAnother: "สร้างใหม่อีกครั้ง", mnemonic12: "วลีช่วยจำ (12 คำ)", copyMnemonic: "คัดลอกวลีช่วยจำ", backupWarning: "สำรองคีย์ส่วนตัวและวลีช่วยจำทันที", saveToVault: "บันทึกลงตู้เซฟ", walletCreated: "สร้างกระเป๋าเงินและบันทึกแล้ว", walletAdded: "เพิ่มกระเป๋าเงินลงตู้เซฟแล้ว", walletAddedDuplicate: "เพิ่มกระเป๋าเงินแล้ว (ที่อยู่ซ้ำ)", addressExplain: "ที่อยู่สาธารณะของกระเป๋าเงิน ปลอดภัยที่จะแชร์", pkExplain: "คีย์ลับที่ควบคุมกระเป๋าเงินนี้ ห้ามแชร์เด็ดขาด", seedExplain: "12 หรือ 24 คำที่สามารถสร้างคีย์ส่วนตัวใหม่ได้ เก็บแบบออฟไลน์", network: "Network", scanQR: "Scan QR" },
  walletCard: { unnamed: "กระเป๋าเงินไม่มีชื่อ", noAddress: "ไม่มีที่อยู่", balanceLabel: "ยอดคงเหลือ", rename: "เปลี่ยนชื่อ", delete: "ลบ", edit: "แก้ไข", editWallet: "แก้ไขกระเป๋าเงิน", saveChanges: "บันทึกการเปลี่ยนแปลง", saved: "บันทึกการเปลี่ยนแปลงแล้ว", added: "เพิ่มเมื่อ", address: "ที่อยู่", privateKey: "คีย์ส่วนตัว", seedPhrase: "วลีช่วยจำ", notes: "บันทึก", notesPlaceholder: "บันทึก...", autoHide: "(ซ่อนอัตโนมัติใน 30 วินาที)", pkWarning: "ใครก็ตามที่มีคีย์นี้จะควบคุมกระเป๋าเงินได้อย่างสมบูรณ์", pin: "Pin", unpin: "Unpin", pinned: "Pinned", network: "Network", clipboardCleared: "Clipboard cleared", masterPasswordRequired: "Enter master password", masterPasswordWrong: "Wrong password", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "Search by address, name, notes...", allWallets: "กระเป๋าเงินทั้งหมด", hasPk: "มีคีย์ส่วนตัว", hasSeed: "มีวลีช่วยจำ", hasBalance: "ยอดคงเหลือ > 0", empty: "ยอดคงเหลือ = 0", defaultOrder: "ลำดับเริ่มต้น", nameAsc: "ชื่อ A → Z", nameDesc: "ชื่อ Z → A", newestFirst: "ใหม่สุดก่อน", oldestFirst: "เก่าสุดก่อน", balanceHigh: "ยอดเงิน สูง → ต่ำ", balanceLow: "ยอดเงิน ต่ำ → สูง", addressAsc: "ที่อยู่ A → Z", allNetworks: "All Networks", pinned: "Pinned", byChain: "By Chain" },
  duplicates: { title: "ตัวตรวจจับรายการซ้ำ", noDuplicates: "ไม่พบรายการซ้ำ", allUnique: "ที่อยู่กระเป๋าเงินทั้งหมดไม่ซ้ำกัน", foundGroups: "พบ {count} ที่อยู่ที่มีรายการซ้ำ", hasPK: "มี PK" },
  dashboard: { title: "การวิเคราะห์", totalWallets: "กระเป๋าเงินทั้งหมด", activeBalance: "ใช้งาน (ยอดเงิน > 0)", emptyWallets: "กระเป๋าเงินว่าง", withPK: "มีคีย์ส่วนตัว", distribution: "การกระจายสินทรัพย์ตามโฟลเดอร์", folders: "โฟลเดอร์", totalValue: "มูลค่ารวมตู้เซฟ", withSeed: "With Seed", chainDistribution: "By Network", importTimeline: "Timeline", networks: "networks", walletsAdded: "added" },
  exportCSV: { title: "ส่งออก CSV", selectColumns: "เลือกคอลัมน์ ({count} กระเป๋าเงิน)", sensitiveWarning: "ข้อมูลที่ละเอียดอ่อนจะถูกส่งออกเป็นข้อความธรรมดา โปรดระมัดระวัง", copy: "คัดลอก", download: "ดาวน์โหลด", copySuccess: "คัดลอก {count} กระเป๋าเงินไปยังคลิปบอร์ด", exportSuccess: "ส่งออก CSV สำเร็จ", colName: "ชื่อ", colAddress: "ที่อยู่", colBalance: "ยอดคงเหลือ", colFolder: "โฟลเดอร์", colPrivateKey: "คีย์ส่วนตัว", colSeedPhrase: "วลีช่วยจำ", colNetwork: "Network" },
  authError: { vaultLocked: "ตู้เซฟถูกล็อค", retry: "ลองยืนยันตัวตนอีกครั้ง", wipeReset: "ลบตู้เซฟและรีเซ็ต", wipeExplain: "คีย์เข้ารหัสสูญหายหรือเสียหาย ข้อมูลทั้งหมดจะถูกลบถาวร", confirmWipe: "ยืนยันการลบ", wiping: "กำลังลบ..." },
  onboarding: { slide1Title: "100% Offline", slide1Desc: "Keys never leave your device.", slide2Title: "Military Encryption", slide2Desc: "Double AES-256 with biometrics.", slide3Title: "Portable Backups", slide3Desc: "Password-protected backup files.", next: "Next", skip: "Skip", getStarted: "Get Started" },
  qrScanner: { title: "Scan QR Code", hint: "Point camera at a QR code" },

  chainBulk: { title: 'ป้ายกำกับ Chain', manualMode: 'เลือกด้วยตัวเอง', autoMode: 'ตรวจจับอัตโนมัติ', targetChain: 'Chain เป้าหมาย', filterBy: 'กรอง', allWallets: 'กระเป๋าทั้งหมด', selectAll: 'เลือกทั้งหมด', deselectAll: 'ยกเลิกทั้งหมด', apply: 'ใช้ {chain} กับ {count} กระเป๋า', updated: 'อัปเดต {count} กระเป๋าเป็น {chain}', autoDesc: 'ตรวจจับ Chain อัตโนมัติตามรูปแบบที่อยู่', evmNote: 'ต้องเลือกด้วยตัวเอง', runAutoDetect: 'เรียกใช้ตรวจจับอัตโนมัติ' },
};
