export default {
  common: { cancel: "İptal", save: "Kaydet", delete: "Sil", close: "Kapat", confirm: "Onayla", copied: "Kopyalandı!", copyData: "Veriyi Kopyala", copiedClipboard: "Panoya kopyalandı" },
  home: { title: "xKey", totalAssets: "Toplam Varlıklar", offlineVault: "Çevrimdışı Kasa", importCSV: "Güvenli CSV İçe Aktar", importDesc: "Verileriniz şifrelenerek çevrimdışı olarak saklanacaktır.", addWallet: "Cüzdan Ekle", noWallets: "Eşleşen cüzdan bulunamadı.", unlocking: "Kasa açılıyor...", importSuccess: "{folder} klasöründen {count} cüzdan içe aktarıldı", duplicatesSkipped: " ({count} kopya atlandı)", walletDeleted: "Cüzdan silindi", folderDeleted: "\"{name}\" klasörü silindi", backupImported: "Yedek içe aktarıldı: {count} cüzdan", deleteWalletConfirm: "\"{name}\" cüzdanını sil?", deleteFolderConfirm: "\"{name}\" klasöründeki tüm cüzdanları sil?" },
  restore: { title: "Yedeği Geri Yükle", desc: "Bu yedek oluşturulurken kullanılan şifreyi girin.", placeholder: "Yedek şifresi", button: "Geri Yükle", wrongPassword: "Yanlış şifre veya bozuk dosya" },
  settings: { title: "Ayarlar", appearance: "Görünüm", darkMode: "Karanlık Mod", lightMode: "Aydınlık Mod", language: "Dil", languageDesc: "Tercih ettiğiniz dili seçin", backupTitle: "Kasa Yedeği", backupSubtitle: "Şifreli ve taşınabilir — her cihazda çalışır", backupInfo: "Cüzdanlarınız seçtiğiniz şifreyle şifrelenir. Bu yedek herhangi bir cihazda geri yüklenebilir.", createBackup: "Şifreli Yedek Oluştur", backupPassword: "Yedek Şifresi", confirmPassword: "Şifreyi Onayla", passwordMin: "Min. 6 karakter", reenterPassword: "Şifreyi tekrar girin", passwordWarning: "Bu şifreyi unutursanız yedek kurtarılamaz.", exportBackup: "Yedeği Dışa Aktar", exporting: "Dışa aktarılıyor...", passwordMinError: "Şifre en az 6 karakter olmalıdır", passwordMismatch: "Şifreler uyuşmuyor", exportSuccess: "Taşınabilir yedek başarıyla dışa aktarıldı", exportFailed: "Dışa aktarma başarısız.", exportError: "Yedek dışa aktarma hatası.", dangerZone: "Tehlikeli Bölge", dangerSubtitle: "Geri alınamaz yıkıcı işlemler", wipeAll: "Tüm Kasa Verilerini Sil", wipeDesc: "AES şifreleme anahtarını ve tüm şifrelenmiş cüzdanları siler. Kurtarılamaz.", wipeConfirm: "UYARI: Tüm şifrelenmiş cüzdanlar silinecektir. Emin misiniz?", amoledMode: "AMOLED", security: "Security", securityDesc: "Auto-lock, clipboard, master password", autoLock: "Auto-Lock", autoLockSaved: "Saved", customMinutes: "Custom (min)", clipboardClear: "Clipboard Auto-Clear", clipboardSaved: "Saved", customSeconds: "Custom (sec)", masterPassword: "Master Password", masterPasswordDesc: "Extra protection for viewing keys", setMasterPassword: "Set", removeMasterPassword: "Remove", masterPasswordSet: "Enabled", masterPasswordRemoved: "Removed", removeMPConfirm: "Remove master password?", mpEnabled: "On", mpDisabled: "Off" , confirmChange: '{setting} değerini {value} olarak değiştir?' },
  createWallet: { title: "Cüzdan Ekle", tabManual: "Manuel Giriş", tabGenerate: "Rastgele Oluştur", generateInfo: "Güvenli rastgele özel anahtar ve anımsatıcı ifadeyle yeni bir cüzdan oluşturun.", generateExplain: "Cüzdanlar saf matematikle oluşturulur — internet gerekmez. Tohum ifadesi BIP-39 standardını takip eder ve uyumlu herhangi bir cüzdanda çalışır.", walletName: "Cüzdan Adı", walletNamePlaceholder: "Ör: Ana Cüzdanım", address: "Adres", addressRequired: "(gerekli)", privateKey: "Özel Anahtar", seedPhrase: "Tohum İfadesi", balance: "Bakiye", notes: "Notlar", notesPlaceholder: "Bu cüzdan hakkında notlar...", optional: "(isteğe bağlı)", duplicateWarning: "Bu adres zaten kasanızda var", fillRequired: "En az bir adres, özel anahtar veya tohum ifadesi girin", generateButton: "Cüzdan Oluştur", generateAnother: "Başka bir tane oluştur", mnemonic12: "Anımsatıcı (12 kelime)", copyMnemonic: "Anımsatıcıyı kopyala", backupWarning: "Özel Anahtarınızı ve Anımsatıcınızı ŞİMDİ yedekleyin.", saveToVault: "Kasaya Kaydet", walletCreated: "Cüzdan oluşturuldu ve kaydedildi", walletAdded: "Cüzdan kasaya eklendi", walletAddedDuplicate: "Cüzdan eklendi (yinelenen adres)", addressExplain: "Cüzdanın genel adresi. Paylaşmak güvenlidir.", pkExplain: "Bu cüzdanı kontrol eden gizli anahtar. ASLA paylaşmayın.", seedExplain: "Özel anahtarı yeniden oluşturabilen 12 veya 24 kelime. Çevrimdışı saklayın.", network: "Network", scanQR: "Scan QR" },
  walletCard: { unnamed: "İsimsiz Cüzdan", noAddress: "Adres Yok", balanceLabel: "Bakiye", rename: "Yeniden Adlandır", delete: "Sil", edit: "Düzenle", editWallet: "Cüzdanı Düzenle", saveChanges: "Değişiklikleri Kaydet", saved: "Değişiklikler kaydedildi", added: "Eklendi", address: "Adres", privateKey: "Özel Anahtar", seedPhrase: "Tohum İfadesi", notes: "Notlar", notesPlaceholder: "Notlar...", autoHide: "(30 saniye sonra otomatik gizle)", pkWarning: "Bu anahtara sahip olan herkes cüzdanı tam olarak kontrol edebilir.", pin: "Pin", unpin: "Unpin", pinned: "Pinned", network: "Network", clipboardCleared: "Clipboard cleared", masterPasswordRequired: "Enter master password", masterPasswordWrong: "Wrong password", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "Search by address, name, notes...", allWallets: "Tüm Cüzdanlar", hasPk: "Özel Anahtarı Var", hasSeed: "Tohum İfadesi Var", hasBalance: "Bakiye > 0", empty: "Bakiye = 0", defaultOrder: "Varsayılan Sıra", nameAsc: "Ad A → Z", nameDesc: "Ad Z → A", newestFirst: "En Yeni", oldestFirst: "En Eski", balanceHigh: "Bakiye Yüksek → Düşük", balanceLow: "Bakiye Düşük → Yüksek", addressAsc: "Adres A → Z", allNetworks: "All Networks", pinned: "Pinned", byChain: "By Chain" },
  duplicates: { title: "Kopya Dedektörü", noDuplicates: "Kopya bulunamadı", allUnique: "Tüm cüzdan adresleri benzersiz.", foundGroups: "{count} adres(ler)de kopya girdiler bulundu.", hasPK: "PK Var" },
  dashboard: { title: "Analitik", totalWallets: "Toplam Cüzdan", activeBalance: "Aktif (Bakiye > 0)", emptyWallets: "Boş Cüzdanlar", withPK: "Özel Anahtarlı", distribution: "Klasöre Göre Varlık Dağılımı", folders: "klasör", totalValue: "Toplam Kasa Değeri", withSeed: "With Seed", chainDistribution: "By Network", importTimeline: "Timeline", networks: "networks", walletsAdded: "added" },
  exportCSV: { title: "CSV Dışa Aktar", selectColumns: "Sütunları seçin ({count} cüzdan)", sensitiveWarning: "Hassas veriler düz metin olarak dışa aktarılacaktır. Son derece dikkatli olun.", copy: "Kopyala", download: "İndir", copySuccess: "{count} cüzdan panoya kopyalandı", exportSuccess: "CSV başarıyla dışa aktarıldı", colName: "Ad", colAddress: "Adres", colBalance: "Bakiye", colFolder: "Klasör", colPrivateKey: "Özel Anahtar", colSeedPhrase: "Tohum İfadesi", colNetwork: "Network" },
  authError: { vaultLocked: "Kasa Kilitli", retry: "Yeniden Dene", wipeReset: "Kasayı Sil ve Sıfırla", wipeExplain: "Şifreleme anahtarınız kayboldu veya bozuldu. Tüm kasa verileri kalıcı olarak silinecektir.", confirmWipe: "Silmeyi Onayla", wiping: "Siliniyor..." },
  onboarding: { slide1Title: "100% Offline", slide1Desc: "Keys never leave your device.", slide2Title: "Military Encryption", slide2Desc: "Double AES-256 with biometrics.", slide3Title: "Portable Backups", slide3Desc: "Password-protected backup files.", next: "Next", skip: "Skip", getStarted: "Get Started" },
  qrScanner: { title: "Scan QR Code", hint: "Point camera at a QR code" },

  chainBulk: { title: 'Zincir Etiketleri', manualMode: 'Manuel Seçim', autoMode: 'Otomatik Algılama', targetChain: 'Hedef Zincir', filterBy: 'Filtrele', allWallets: 'Tüm Cüzdanlar', selectAll: 'Tümünü Seç', deselectAll: 'Tümünü Kaldır', apply: '{count} cüzdana {chain} uygula', updated: '{count} cüzdan {chain} olarak güncellendi', autoDesc: 'Adres formatına göre otomatik zincir algılama.', evmNote: 'manuel seçim gerekli', runAutoDetect: 'Otomatik Algılamayı Çalıştır' },
};
