export default {
  common: { cancel: "Hủy", save: "Lưu", delete: "Xóa", close: "Đóng", confirm: "Xác nhận", copied: "Đã sao chép!", copyData: "Sao chép dữ liệu", copiedClipboard: "Đã sao chép vào clipboard" },
  home: { title: "xKey", totalAssets: "Tổng tài sản", offlineVault: "Kho ngoại tuyến", importCSV: "Nhập CSV an toàn", importDesc: "Dữ liệu sẽ được mã hóa và lưu trữ cục bộ ngoại tuyến.", addWallet: "Thêm ví", noWallets: "Không tìm thấy ví phù hợp.", unlocking: "Đang mở kho...", importSuccess: "Đã nhập {count} ví từ {folder}", duplicatesSkipped: " (bỏ qua {count} trùng lặp)", walletDeleted: "Đã xóa ví", folderDeleted: "Đã xóa thư mục \"{name}\"", backupImported: "Đã nhập bản sao lưu: {count} ví", deleteWalletConfirm: "Xóa ví \"{name}\"?", deleteFolderConfirm: "Xóa tất cả ví trong thư mục \"{name}\"?" },
  restore: { title: "Khôi phục bản sao lưu", desc: "Nhập mật khẩu đã dùng khi tạo bản sao lưu này.", placeholder: "Mật khẩu sao lưu", button: "Khôi phục", wrongPassword: "Sai mật khẩu hoặc tệp bị hỏng" },
  settings: { title: "Cài đặt", appearance: "Giao diện", darkMode: "Chế độ tối", lightMode: "Chế độ sáng", language: "Ngôn ngữ", languageDesc: "Chọn ngôn ngữ ưa thích", backupTitle: "Sao lưu kho", backupSubtitle: "Mã hóa & di động — hoạt động trên mọi thiết bị", backupInfo: "Ví của bạn được mã hóa bằng mật khẩu bạn chọn. Bản sao lưu này có thể khôi phục trên bất kỳ thiết bị nào — kể cả sau khi xóa dữ liệu.", createBackup: "Tạo bản sao lưu mã hóa", backupPassword: "Mật khẩu sao lưu", confirmPassword: "Xác nhận mật khẩu", passwordMin: "Tối thiểu 6 ký tự", reenterPassword: "Nhập lại mật khẩu", passwordWarning: "Nếu quên mật khẩu này, bản sao lưu không thể khôi phục.", exportBackup: "Xuất bản sao lưu", exporting: "Đang xuất...", passwordMinError: "Mật khẩu phải ít nhất 6 ký tự", passwordMismatch: "Mật khẩu không khớp", exportSuccess: "Đã xuất bản sao lưu di động thành công", exportFailed: "Xuất thất bại.", exportError: "Lỗi khi xuất bản sao lưu.", dangerZone: "Vùng nguy hiểm", dangerSubtitle: "Hành động phá hủy không thể hoàn tác", wipeAll: "Xóa toàn bộ dữ liệu kho", wipeDesc: "Hành động này xóa Khóa Mã hóa AES và tất cả ví đã mã hóa. Không thể khôi phục.", wipeConfirm: "CẢNH BÁO: Tất cả ví mã hóa sẽ bị xóa khỏi thiết bị này. Bạn sẽ mất quyền truy cập kho này. Bạn chắc chứ?", amoledMode: "AMOLED", security: "Bảo mật", securityDesc: "Khóa tự động, clipboard, mật khẩu chính", autoLock: "Thời gian tự khóa", autoLockSaved: "Đã lưu thời gian tự khóa", customMinutes: "Tùy chỉnh (phút)", clipboardClear: "Tự xóa clipboard", clipboardSaved: "Đã lưu thời gian clipboard", customSeconds: "Tùy chỉnh (giây)", masterPassword: "Mật khẩu chính", masterPasswordDesc: "Lớp bảo vệ thêm khi xem Khóa Riêng Tư và Cụm Từ", setMasterPassword: "Đặt mật khẩu chính", removeMasterPassword: "Xóa mật khẩu chính", masterPasswordSet: "Đã bật mật khẩu chính", masterPasswordRemoved: "Đã xóa mật khẩu chính", removeMPConfirm: "Xóa mật khẩu chính?", mpEnabled: "Đã bật", mpDisabled: "Tắt" , confirmChange: 'Thay đổi {setting} thành {value}?' },
  createWallet: { title: "Thêm ví", tabManual: "Nhập thủ công", tabGenerate: "Tạo ngẫu nhiên", generateInfo: "Tạo ví mới với khóa riêng tư ngẫu nhiên an toàn và cụm từ gợi nhớ.", generateExplain: "Ví được tạo bằng toán học thuần túy — không cần Internet. Số ngẫu nhiên 256 bit trở thành Khóa Riêng Tư của bạn (nhiều khả năng hơn số nguyên tử trong vũ trụ). Cụm từ gợi nhớ tuân theo chuẩn BIP-39 nên hoạt động trên mọi ví tương thích (MetaMask, Trust Wallet, OKX Wallet, v.v.).", walletName: "Tên ví", walletNamePlaceholder: "VD: Ví chính của tôi", address: "Địa chỉ", addressRequired: "(bắt buộc)", privateKey: "Khóa riêng tư", seedPhrase: "Cụm từ gợi nhớ", balance: "Số dư", notes: "Ghi chú", notesPlaceholder: "Ghi chú về ví này...", optional: "(tùy chọn)", duplicateWarning: "Địa chỉ này đã tồn tại trong kho của bạn", fillRequired: "Vui lòng điền ít nhất một địa chỉ, khóa riêng tư hoặc cụm từ gợi nhớ", generateButton: "Tạo ví", generateAnother: "Tạo ví khác", mnemonic12: "Cụm từ gợi nhớ (12 từ)", copyMnemonic: "Sao chép cụm từ gợi nhớ", backupWarning: "Sao lưu Khóa Riêng Tư và Cụm Từ Gợi Nhớ NGAY. Chúng sẽ được mã hóa sau khi lưu và không thể khôi phục nếu mất thiết bị mà không có bản sao lưu.", saveToVault: "Lưu vào kho", walletCreated: "Đã tạo ví và lưu vào kho", walletAdded: "Đã thêm ví vào kho", walletAddedDuplicate: "Đã thêm ví (địa chỉ trùng)", addressExplain: "Địa chỉ công khai của ví (bắt đầu bằng 0x cho chuỗi EVM). An toàn để chia sẻ — như số tài khoản ngân hàng.", pkExplain: "Khóa bí mật kiểm soát ví này. Bất kỳ ai có khóa riêng tư đều có thể tiêu hết tiền. KHÔNG BAO GIỜ chia sẻ.", seedExplain: "12 hoặc 24 từ có thể tạo lại khóa riêng tư. Lưu trữ ngoại tuyến, không chụp màn hình hay chia sẻ.", network: "Mạng lưới", scanQR: "Quét QR" },
  walletCard: { unnamed: "Ví chưa đặt tên", noAddress: "Không có địa chỉ", balanceLabel: "Số dư", rename: "Đổi tên", delete: "Xóa", edit: "Sửa", editWallet: "Chỉnh sửa ví", saveChanges: "Lưu thay đổi", saved: "Đã lưu thay đổi", added: "Đã thêm", address: "Địa chỉ", privateKey: "Khóa riêng tư", seedPhrase: "Cụm từ gợi nhớ", notes: "Ghi chú", notesPlaceholder: "Ghi chú...", autoHide: "(ẩn tự động sau 30 giây)", pkWarning: "Bất kỳ ai có khóa này đều toàn quyền kiểm soát ví.", pin: "Ghim", unpin: "Bỏ ghim", pinned: "Đã ghim", network: "Mạng lưới", clipboardCleared: "Đã xóa clipboard", masterPasswordRequired: "Nhập mật khẩu chính để xem", masterPasswordWrong: "Sai mật khẩu chính", changeNetwork: "Chạm để đổi mạng" },
  actionBar: { searchPlaceholder: "Tìm theo địa chỉ, tên, ghi chú...", allWallets: "Tất cả ví", hasPk: "Có khóa riêng tư", hasSeed: "Có cụm từ gợi nhớ", hasBalance: "Số dư > 0", empty: "Số dư = 0", defaultOrder: "Thứ tự mặc định", nameAsc: "Tên A → Z", nameDesc: "Tên Z → A", newestFirst: "Mới nhất trước", oldestFirst: "Cũ nhất trước", balanceHigh: "Số dư cao → thấp", balanceLow: "Số dư thấp → cao", addressAsc: "Địa chỉ A → Z", allNetworks: "Tất cả mạng", pinned: "Đã ghim", byChain: "Theo chuỗi" },
  duplicates: { title: "Phát hiện trùng lặp", noDuplicates: "Không tìm thấy trùng lặp", allUnique: "Tất cả địa chỉ ví đều duy nhất.", foundGroups: "Tìm thấy {count} địa chỉ có mục trùng lặp. Xem lại và xóa những mục không cần.", hasPK: "Có PK" },
  dashboard: { title: "Phân tích", totalWallets: "Tổng số ví", activeBalance: "Hoạt động (Số dư > 0)", emptyWallets: "Ví trống", withPK: "Có khóa riêng tư", distribution: "Phân bổ tài sản theo thư mục", folders: "thư mục", totalValue: "Tổng giá trị kho", withSeed: "Có cụm từ gợi nhớ", chainDistribution: "Phân bổ theo mạng", importTimeline: "Lịch sử nhập", networks: "mạng", walletsAdded: "ví đã thêm" },
  exportCSV: { title: "Xuất CSV", selectColumns: "Chọn cột để xuất ({count} ví)", sensitiveWarning: "Dữ liệu nhạy cảm (Khóa Riêng Tư / Cụm Từ) sẽ được xuất dạng văn bản thuần. Xử lý cực kỳ cẩn thận.", copy: "Sao chép", download: "Tải xuống", copySuccess: "Đã sao chép {count} ví vào clipboard", exportSuccess: "Đã xuất CSV thành công", colName: "Tên", colAddress: "Địa chỉ", colBalance: "Số dư", colFolder: "Thư mục", colPrivateKey: "Khóa riêng tư", colSeedPhrase: "Cụm từ gợi nhớ", colNetwork: "Mạng lưới" },
  authError: { vaultLocked: "Kho bị khóa", retry: "Thử xác thực lại", wipeReset: "Xóa kho & đặt lại", wipeExplain: "Khóa mã hóa của bạn đã bị mất hoặc hỏng (thường xảy ra khi bạn xóa khóa màn hình điện thoại). Tất cả dữ liệu kho sẽ bị xóa vĩnh viễn.", confirmWipe: "Xác nhận xóa", wiping: "Đang xóa..." },
  onboarding: { slide1Title: "Bảo mật 100% ngoại tuyến", slide1Desc: "Khóa riêng tư không bao giờ rời thiết bị.", slide2Title: "Mã hóa cấp quân sự", slide2Desc: "Mã hóa AES-256 hai lớp với xác thực sinh trắc.", slide3Title: "Sao lưu di động", slide3Desc: "Tạo tệp sao lưu bảo vệ bằng mật khẩu.", next: "Tiếp", skip: "Bỏ qua", getStarted: "Bắt đầu" },
  qrScanner: { title: "Quét mã QR", hint: "Hướng camera vào mã QR chứa địa chỉ hoặc khóa" },

  chainBulk: { title: 'Nhãn Chain', manualMode: 'Chọn thủ công', autoMode: 'Tự phát hiện', targetChain: 'Chain đích', filterBy: 'Lọc theo', allWallets: 'Tất cả ví', selectAll: 'Chọn tất cả', deselectAll: 'Bỏ chọn tất cả', apply: 'Áp dụng {chain} cho {count} ví', updated: 'Đã cập nhật {count} ví sang {chain}', autoDesc: 'Tự phát hiện chain dựa trên định dạng địa chỉ. Các chain không phải EVM (Tron, Solana) sẽ được gắn nhãn tự động.', evmNote: 'cần chọn thủ công', runAutoDetect: 'Chạy phát hiện tự động' },
};
