export default {
  common: { cancel: "取消", save: "保存", delete: "删除", close: "关闭", confirm: "确认", copied: "已复制！", copyData: "复制数据", copiedClipboard: "已复制到剪贴板" },
  home: { title: "xKey", totalAssets: "总资产", offlineVault: "离线密钥库", importCSV: "导入安全CSV", importDesc: "您的数据将被加密并离线存储在本地。", addWallet: "添加钱包", noWallets: "未找到匹配的钱包。", unlocking: "正在解锁密钥库...", importSuccess: "从 {folder} 导入了 {count} 个钱包", duplicatesSkipped: "（跳过 {count} 个重复）", walletDeleted: "钱包已删除", folderDeleted: "文件夹 \"{name}\" 已删除", backupImported: "已导入备份：{count} 个钱包", deleteWalletConfirm: "删除钱包 \"{name}\"？", deleteFolderConfirm: "删除文件夹 \"{name}\" 中的所有钱包？" },
  restore: { title: "恢复备份", desc: "输入创建此备份时使用的密码。", placeholder: "备份密码", button: "恢复", wrongPassword: "密码错误或文件损坏" },
  settings: { title: "设置", appearance: "外观", darkMode: "深色模式", lightMode: "浅色模式", language: "语言", languageDesc: "选择您的首选语言", backupTitle: "密钥库备份", backupSubtitle: "加密便携 — 适用于任何设备", backupInfo: "您的钱包使用您选择的密码加密。此备份可在任何设备上恢复 — 即使在清除数据之后。", createBackup: "创建加密备份", backupPassword: "备份密码", confirmPassword: "确认密码", passwordMin: "最少6个字符", reenterPassword: "重新输入密码", passwordWarning: "如果忘记此密码，备份将无法恢复。", exportBackup: "导出备份", exporting: "导出中...", passwordMinError: "密码至少需要6个字符", passwordMismatch: "密码不匹配", exportSuccess: "便携式备份导出成功", exportFailed: "导出失败。", exportError: "导出备份时出错。", dangerZone: "危险区域", dangerSubtitle: "不可逆的破坏性操作", wipeAll: "清除所有密钥库数据", wipeDesc: "此操作将删除AES加密密钥和所有加密钱包。无法恢复。", wipeConfirm: "警告：此设备上的所有加密钱包将被删除。您将失去对此密钥库的访问权限。确定吗？", amoledMode: "AMOLED", security: "安全", securityDesc: "自动锁定、剪贴板、主密码", autoLock: "自动锁定时间", autoLockSaved: "已保存", customMinutes: "自定义（分钟）", clipboardClear: "自动清除剪贴板", clipboardSaved: "已保存", customSeconds: "自定义（秒）", masterPassword: "主密码", masterPasswordDesc: "查看私钥时的额外保护", setMasterPassword: "设置主密码", removeMasterPassword: "移除主密码", masterPasswordSet: "已启用", masterPasswordRemoved: "已移除", removeMPConfirm: "移除主密码？", mpEnabled: "已启用", mpDisabled: "未启用" , confirmChange: '将{setting}更改为{value}？' },
  createWallet: { title: "添加钱包", tabManual: "手动输入", tabGenerate: "随机生成", generateInfo: "使用安全随机私钥和助记词生成全新钱包。", generateExplain: "钱包通过纯数学创建 — 无需互联网。256位随机数成为您的私钥（可能性比宇宙中的原子还多）。助记词遵循BIP-39标准，可在任何兼容钱包上使用（MetaMask、Trust Wallet、OKX Wallet等）。", walletName: "钱包名称", walletNamePlaceholder: "例：我的主钱包", address: "地址", addressRequired: "（必填）", privateKey: "私钥", seedPhrase: "助记词", balance: "余额", notes: "备注", notesPlaceholder: "关于此钱包的备注...", optional: "（可选）", duplicateWarning: "此地址已存在于您的密钥库中", fillRequired: "请至少填写一个地址、私钥或助记词", generateButton: "生成钱包", generateAnother: "再次生成", mnemonic12: "助记词（12个词）", copyMnemonic: "复制助记词", backupWarning: "立即备份您的私钥和助记词。保存后将被加密，如果没有备份丢失设备将无法恢复。", saveToVault: "保存到密钥库", walletCreated: "钱包已创建并保存", walletAdded: "钱包已添加到密钥库", walletAddedDuplicate: "钱包已添加（地址重复）", addressExplain: "钱包的公共地址（EVM链以0x开头）。可以安全分享 — 就像银行账号。", pkExplain: "控制此钱包的密钥。任何拥有私钥的人都可以花费所有资金。切勿分享。", seedExplain: "12或24个单词可以重新生成私钥。离线存储，不要截图或分享。", network: "网络", scanQR: "扫描QR" },
  walletCard: { unnamed: "未命名钱包", noAddress: "无地址", balanceLabel: "余额", rename: "重命名", delete: "删除", edit: "编辑", editWallet: "编辑钱包", saveChanges: "保存更改", saved: "更改已保存", added: "添加于", address: "地址", privateKey: "私钥", seedPhrase: "助记词", notes: "备注", notesPlaceholder: "备注...", autoHide: "（30秒后自动隐藏）", pkWarning: "拥有此密钥的任何人都可以完全控制钱包。", pin: "置顶", unpin: "取消置顶", pinned: "已置顶", network: "网络", clipboardCleared: "已清除", masterPasswordRequired: "输入主密码", masterPasswordWrong: "密码错误", changeNetwork: "Change network" },
  actionBar: { searchPlaceholder: "按地址、名称、备注搜索...", allWallets: "所有钱包", hasPk: "有私钥", hasSeed: "有助记词", hasBalance: "余额 > 0", empty: "余额 = 0", defaultOrder: "默认排序", nameAsc: "名称 A → Z", nameDesc: "名称 Z → A", newestFirst: "最新优先", oldestFirst: "最旧优先", balanceHigh: "余额 高 → 低", balanceLow: "余额 低 → 高", addressAsc: "地址 A → Z", allNetworks: "所有网络", pinned: "已置顶", byChain: "By Chain" },
  duplicates: { title: "重复检测器", noDuplicates: "未找到重复", allUnique: "所有钱包地址均唯一。", foundGroups: "发现 {count} 个地址有重复条目。请审查并删除不需要的条目。", hasPK: "有PK" },
  dashboard: { title: "分析", totalWallets: "钱包总数", activeBalance: "活跃（余额 > 0）", emptyWallets: "空钱包", withPK: "有私钥", distribution: "按文件夹的资产分布", folders: "文件夹", totalValue: "密钥库总价值", withSeed: "有助记词", chainDistribution: "按链分布", importTimeline: "导入时间线", networks: "链", walletsAdded: "已添加" },
  exportCSV: { title: "导出CSV", selectColumns: "选择要包含的列（{count} 个钱包）", sensitiveWarning: "敏感数据（私钥/助记词）将以明文导出。请极其谨慎处理。", copy: "复制", download: "下载", copySuccess: "已复制 {count} 个钱包到剪贴板", exportSuccess: "CSV导出成功", colName: "名称", colAddress: "地址", colBalance: "余额", colFolder: "文件夹", colPrivateKey: "私钥", colSeedPhrase: "助记词", colNetwork: "网络" },
  authError: { vaultLocked: "密钥库已锁定", retry: "重试认证", wipeReset: "清除密钥库并重置", wipeExplain: "您的加密密钥已丢失或损坏。所有密钥库数据将被永久删除。", confirmWipe: "确认清除", wiping: "正在清除..." },
  onboarding: { slide1Title: "100%离线安全", slide1Desc: "私钥永远不会离开设备。", slide2Title: "军事级加密", slide2Desc: "双层AES-256加密与生物认证。", slide3Title: "便携式备份", slide3Desc: "密码保护的备份文件。", next: "下一步", skip: "跳过", getStarted: "开始" },
  qrScanner: { title: "扫描二维码", hint: "将相机对准QR码" },

  chainBulk: { title: '链标签', manualMode: '手动选择', autoMode: '自动检测', targetChain: '目标链', filterBy: '筛选', allWallets: '所有钱包', selectAll: '全选', deselectAll: '取消全选', apply: '将{chain}应用于{count}个钱包', updated: '{count}个钱包已更新为{chain}', autoDesc: '根据地址格式自动检测链。非EVM链（Tron、Solana）将自动标记。', evmNote: '需手动选择', runAutoDetect: '运行自动检测' },
};
